// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Usar el pooler para runtime
    url: process.env.DATABASE_URL || "",
    // Usar la directa para migraciones (aunque falle localmente, Vercel la usará)
    directUrl: process.env.DIRECT_URL || "",
  },
});
